# Generated by Django 4.0.6 on 2022-07-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.CharField(choices=[('UGX', 'UGX'), ('Dollar', 'Dollar')], default='UGX', max_length=10, null=True),
        ),
    ]
