# Generated by Django 4.0.6 on 2022-07-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_transaction_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
    ]
